#!/bin/bash

#Wrapper to override task rc file forcing task list data to be located in the current directory.
#Author:	Ruben Westerberg
#Date:		Wed  3 May 2017 12:17:53 AEST

#If a symbolic link is used, the relative path of the data is all wrong. We
#want the dir where the todo dir actually is cloned to!

link=$(readlink $0);
base=$(dirname $0);
TODO=$base/$link;

#Executing the todo scrpt in the local directory has the path we need
dir=$(dirname $TODO);

#Pass the command line arguments to the actual taskwarrior process
task rc.data.location=$dir $@
